language: ruby
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq time
 - sudo apt-get install -qq lua5.1
 - which gem
 - rvm list
 - rvm gemdir
 - sudo gem list
 - sudo gem install --verbose json
script: "make build"
rvm:
 - 1.8.7
 - 1.9.3
