language: ruby
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq time
 - sudo apt-get install -qq lua5.1
 - which gem
 - rvm list
 - rvm gemdir
 - find ~/.rvm | grep 1.8 | grep json
 - find ~/.rvm | grep 1.9 | grep json
 - printenv
 - sudo gem list
 - ruby -e 'puts $LOAD_PATH'
script: "make build"
rvm:
 - 1.8.7
 - 1.9.3
